name: build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          mysql:
            image: mysql:8.0
            env:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: test
            ports:
              - 3306:3306
            options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '9.0.x'
            - name: Set env
              run: |
                echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
                echo "DOTNET_hostBuilder:reloadConfigOnChange=false" >> $GITHUB_ENV
            - uses: dotnet/nbgv@master
              id: nbgv
            - name: Clean
              run: |
                dotnet clean ./SuperSocket.MySQL.sln --configuration Release
                dotnet nuget locals all --clear
            - name: Build
              run: dotnet build -c Debug
            - name: Setup MySQL auth
              run: |
                mysql -h 127.0.0.1 -u root -proot -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root'; FLUSH PRIVILEGES;"
            - name: Test
              run: |
                cd tests/SuperSocket.MySQL.Test
                dotnet test
            - name: Pack
              run: dotnet pack -c Release -p:PackageVersion=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }} -p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }} -p:AssemblyVersion=${{ steps.nbgv.outputs.AssemblyVersion }} -p:AssemblyFileVersion=${{ steps.nbgv.outputs.AssemblyFileVersion }} -p:AssemblyInformationalVersion=${{ steps.nbgv.outputs.AssemblyInformationalVersion }} /p:NoPackageAnalysis=true /p:IncludeReleaseNotes=false
            - name: Push
              run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/supersocket/api/v3/index.json